server:
  port: 9090

spring:
  datasource:
#    driver-class-name: spring.datasource.driver-class-name=org.postgresql.Driver
#      url: jdbc:postgresql://192.168.1.109:5432/postgres?serverTimezone=GMT%2b8
      url: jdbc:postgresql://localhost:5432/postgres2?serverTimezone=GMT%2b8
      username: postgres
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

